# Generated by Django 4.2 on 2024-07-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skype_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
